/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py:177: RuntimeWarning: invalid value encountered in log10
  return m0 - 2.5*np.log10((1-fb)*A+fb)
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 416, in <module>
    testUnet_KMT2019(posi,network_res,network_ref,thres=0.999,thres_ref=0.998)
  File "/home/zerui603/MDN_lc_iden/unet/unet_kmt_500.py", line 324, in testUnet_KMT2019
    KMT_args,data_total,data_A,data_C,data_S,_ = loaddata.getKMTdata(posi=posi,cutratio=[-2*new_cutratio+new_correctratio,2*new_cutratio+new_correctratio],FWHM_threshold=50,sky_threshold=20000)
  File "/home/zerui603/MDN_lc_iden/unet/datamodule/loaddata.py", line 130, in getKMTdata
    bound_cut = [time_select_index[0],time_select_index[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0
/home/zerui603/MDN_lc_iden/unet/netmodule/unetforkmt_500.py:21: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-u))
